### ISSUE TITLE
Nach dem Export, kann Dialogfeld nicht mehr geschlossen werden

### ISSUE THREAD

**Issue by ThomasStuetz** [BeatingAngel/Testumgebung#58]
Ausserdem sollte der Pfad, zum erstellten Logfile angegeben werden!

<img width="1210" alt="screen shot 2016-10-25 at 10 10 46" src="https://cloud.githubusercontent.com/assets/7039733/19677830/6b46c8d0-9a9b-11e6-9bef-236456950373.png">

**Comment by BeatingAngel** [comment]
Die PopUp-Fenster kann man mit der Enter-Taste schließen. 
Ich werden demnächst da noch einen Close-Button hinzufügen.
