### ISSUE TITLE
Startverzeichnis standardmäßig eingestellt

### ISSUE THREAD

**Issue by MET1** [BeatingAngel/Testumgebung#68]

**Comment by BeatingAngel** [comment]
Die JAR-File sollte erkennen in welchen Order (wo) sie ist, und dies als Standardverzeichnis verwenden.  
  
Zusätzlich sollte in diesem Ordner, wo die JAR ist, nach der Angabe gesucht werden. Ist in dem selben Ordner eine Angabe, dann sollte diese als Handout-File verwendet werden.  
Richtlinien:  die Abgabefile muss eine von diesen 4 Namen haben:
* angabe.png
* angabe.jpg
* angabe.pdf
* angabe.zip  

Es ist casesensitive.
