### ISSUE TITLE
Wie funktioniert der Import und Export von Settings

### ISSUE THREAD

**Issue by htl-leonding** [BeatingAngel/Testumgebung#71]
Teilweise sind die Optionen bei den Advanced Settings kryptisch. Wohin werden die Settings exportiert. Im modalen Fenster sollte der Pfad angegeben werden sowie Dateiname, wohin die Settings exportiert wurden (immer Feedback an User)

Beim Import von Schülerlisten funktioniert gar nichts

![screen shot 2017-02-11 at 09 04 55](https://cloud.githubusercontent.com/assets/14834294/22852322/1feb8dc2-f03a-11e6-8ed8-3fcb09c80ff7.png)

**Comment by BeatingAngel** [comment]
Alles was man exportiert (logs, diagramme, settings,  . . . ) landet in dem export-Ordner.  
Ich werde in dem PopUp-Fenster den Pfad mit Dateiname noch anzeigen lassen.  
  
# Der Student-Import  
Es funktioniert aus folgenden Gründen nicht mehr und wird deswegen **demnächst entfernt**:   

Würde man die Schüler durch eine File hinzufügen, hätte man keine IP-Adressen. Somit würden die Schüler nur in der Liste stehen. Aber wenn sich der echte Schüler anmelden möchte, wird überprüft ob er schon in der Liste ist. Diese Überprüfung läuft mittels der IP-Adresse. Da der Schüler aus der CSV-File keine IP-Adresse hat aber der echte schon, wird dieser als NEU erkannt. Deshalb würde sich der Schülerimport nichts mehr bringen.  
  
Situation 1:
Dieser Vergleich beim Anmelden erfolgt deswegen mittels der IP-Adresse, da es ja sein könnte, dass zwei oder mehr Schüler den gleichen Namen haben (das war schon einmal der Fall in einer 2ten Klasse während ich den Test betreut habe -- gleicher Nachname). 
Situation 2:  
Würde ein anderer Schüler "aus Spaß" den Namen eines anderen Schülers beim Login angeben, würde der vorherige Schüler gekickt werden, was nicht gut wäre.
